# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/6ima1/flavie.enrico/Linux C++/S2/Prog_visu/ProgAlgo"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/6ima1/flavie.enrico/Linux C++/S2/Prog_visu/ProgAlgo"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/6ima1/flavie.enrico/Linux C++/S2/Prog_visu/ProgAlgo/CMakeFiles" "/home/6ima1/flavie.enrico/Linux C++/S2/Prog_visu/ProgAlgo/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/6ima1/flavie.enrico/Linux C++/S2/Prog_visu/ProgAlgo/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P "/home/6ima1/flavie.enrico/Linux C++/S2/Prog_visu/ProgAlgo/CMakeFiles/VerifyGlobs.cmake"
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ProgAlgo

# Build rule for target.
ProgAlgo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ProgAlgo
.PHONY : ProgAlgo

# fast build rule for target.
ProgAlgo/fast:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/build
.PHONY : ProgAlgo/fast

entite.o: entite.cpp.o

.PHONY : entite.o

# target to build an object file
entite.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/entite.cpp.o
.PHONY : entite.cpp.o

entite.i: entite.cpp.i

.PHONY : entite.i

# target to preprocess a source file
entite.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/entite.cpp.i
.PHONY : entite.cpp.i

entite.s: entite.cpp.s

.PHONY : entite.s

# target to generate assembly for a file
entite.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/entite.cpp.s
.PHONY : entite.cpp.s

fonctions.o: fonctions.cpp.o

.PHONY : fonctions.o

# target to build an object file
fonctions.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/fonctions.cpp.o
.PHONY : fonctions.cpp.o

fonctions.i: fonctions.cpp.i

.PHONY : fonctions.i

# target to preprocess a source file
fonctions.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/fonctions.cpp.i
.PHONY : fonctions.cpp.i

fonctions.s: fonctions.cpp.s

.PHONY : fonctions.s

# target to generate assembly for a file
fonctions.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/fonctions.cpp.s
.PHONY : fonctions.cpp.s

gestion_frame.o: gestion_frame.cpp.o

.PHONY : gestion_frame.o

# target to build an object file
gestion_frame.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/gestion_frame.cpp.o
.PHONY : gestion_frame.cpp.o

gestion_frame.i: gestion_frame.cpp.i

.PHONY : gestion_frame.i

# target to preprocess a source file
gestion_frame.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/gestion_frame.cpp.i
.PHONY : gestion_frame.cpp.i

gestion_frame.s: gestion_frame.cpp.s

.PHONY : gestion_frame.s

# target to generate assembly for a file
gestion_frame.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/gestion_frame.cpp.s
.PHONY : gestion_frame.cpp.s

inter_joueur.o: inter_joueur.cpp.o

.PHONY : inter_joueur.o

# target to build an object file
inter_joueur.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/inter_joueur.cpp.o
.PHONY : inter_joueur.cpp.o

inter_joueur.i: inter_joueur.cpp.i

.PHONY : inter_joueur.i

# target to preprocess a source file
inter_joueur.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/inter_joueur.cpp.i
.PHONY : inter_joueur.cpp.i

inter_joueur.s: inter_joueur.cpp.s

.PHONY : inter_joueur.s

# target to generate assembly for a file
inter_joueur.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/inter_joueur.cpp.s
.PHONY : inter_joueur.cpp.s

interf_graph.o: interf_graph.cpp.o

.PHONY : interf_graph.o

# target to build an object file
interf_graph.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/interf_graph.cpp.o
.PHONY : interf_graph.cpp.o

interf_graph.i: interf_graph.cpp.i

.PHONY : interf_graph.i

# target to preprocess a source file
interf_graph.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/interf_graph.cpp.i
.PHONY : interf_graph.cpp.i

interf_graph.s: interf_graph.cpp.s

.PHONY : interf_graph.s

# target to generate assembly for a file
interf_graph.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/interf_graph.cpp.s
.PHONY : interf_graph.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/main.cpp.s
.PHONY : main.cpp.s

niveau_manager.o: niveau_manager.cpp.o

.PHONY : niveau_manager.o

# target to build an object file
niveau_manager.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/niveau_manager.cpp.o
.PHONY : niveau_manager.cpp.o

niveau_manager.i: niveau_manager.cpp.i

.PHONY : niveau_manager.i

# target to preprocess a source file
niveau_manager.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/niveau_manager.cpp.i
.PHONY : niveau_manager.cpp.i

niveau_manager.s: niveau_manager.cpp.s

.PHONY : niveau_manager.s

# target to generate assembly for a file
niveau_manager.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/niveau_manager.cpp.s
.PHONY : niveau_manager.cpp.s

quadtree.o: quadtree.cpp.o

.PHONY : quadtree.o

# target to build an object file
quadtree.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/quadtree.cpp.o
.PHONY : quadtree.cpp.o

quadtree.i: quadtree.cpp.i

.PHONY : quadtree.i

# target to preprocess a source file
quadtree.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/quadtree.cpp.i
.PHONY : quadtree.cpp.i

quadtree.s: quadtree.cpp.s

.PHONY : quadtree.s

# target to generate assembly for a file
quadtree.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/quadtree.cpp.s
.PHONY : quadtree.cpp.s

rectangle.o: rectangle.cpp.o

.PHONY : rectangle.o

# target to build an object file
rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/rectangle.cpp.o
.PHONY : rectangle.cpp.o

rectangle.i: rectangle.cpp.i

.PHONY : rectangle.i

# target to preprocess a source file
rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/rectangle.cpp.i
.PHONY : rectangle.cpp.i

rectangle.s: rectangle.cpp.s

.PHONY : rectangle.s

# target to generate assembly for a file
rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/rectangle.cpp.s
.PHONY : rectangle.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/ProgAlgo.dir/build.make CMakeFiles/ProgAlgo.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ProgAlgo"
	@echo "... edit_cache"
	@echo "... entite.o"
	@echo "... entite.i"
	@echo "... entite.s"
	@echo "... fonctions.o"
	@echo "... fonctions.i"
	@echo "... fonctions.s"
	@echo "... gestion_frame.o"
	@echo "... gestion_frame.i"
	@echo "... gestion_frame.s"
	@echo "... inter_joueur.o"
	@echo "... inter_joueur.i"
	@echo "... inter_joueur.s"
	@echo "... interf_graph.o"
	@echo "... interf_graph.i"
	@echo "... interf_graph.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... niveau_manager.o"
	@echo "... niveau_manager.i"
	@echo "... niveau_manager.s"
	@echo "... quadtree.o"
	@echo "... quadtree.i"
	@echo "... quadtree.s"
	@echo "... rectangle.o"
	@echo "... rectangle.i"
	@echo "... rectangle.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P "/home/6ima1/flavie.enrico/Linux C++/S2/Prog_visu/ProgAlgo/CMakeFiles/VerifyGlobs.cmake"
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

